# Generated by Django 4.1.7 on 2023-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerUsername', models.CharField(max_length=100)),
                ('customerPassword', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=254)),
                ('customerAddress', models.TextField()),
                ('customerImg', models.ImageField(upload_to=None)),
            ],
        ),
    ]
