# Generated by Django 4.1.7 on 2023-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerImg',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
