# Generated by Django 4.1 on 2023-02-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_productimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
