# Generated by Django 4.1 on 2023-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerImg',
            field=models.ImageField(default='static/img/default/customer/default_user.png', upload_to='static/img/customer/'),
        ),
    ]
